nova_username: "admin"
nova_tenantname: "admin"
# NOTE(rpodolyaka): limitation of tuskar-api, see https://bugs.launchpad.net/tuskar/+bug/1235236
nova_password: "{{tuskar.overcloud-admin-password}}"
keystone_url: "http://{{tuskar.overcloud-keystone-host}}:5000/v2.0/"
