#!/bin/bash
set -x

SCRIPTDIR=$(dirname $0)

install -D -g root -o root -m 0755 ${SCRIPTDIR}/hook-chef.py /var/lib/heat-config/hooks/chef

pip install --upgrade python-heatclient

curl https://www.opscode.com/chef/install.sh | bash
