heat_template_version: 2013-05-23

description: demo for real app deployment.

parameters:
  key_name:
    type: string
    description : Name of a key pair to enable SSH access to instances.
    default: yangbo52
  flavor:
    type: string
    description: Flavor to use for the WordPress server.
    default: m1.small
  image:
    type: string
    description: swc/swd image
    default: fedora-software-config
  db_name:
    type: string
    description: WordPress database name
    default: wordpress
  network_id_private:
    type: string
    default: 9c743c4c-2106-403f-bd57-0cee90de32cc
  public_net_id:
    type: string
    default: f65c40f6-3c48-4ff3-aa88-0b0fec9eca16
  db_root_password:
    type: string
    description: WordPress database name
    default: passw0rd
  db_password:
    type: string
    description: WordPress database name
    default: passw0rd
  db_username:
    type: string
    description: The WordPress database admin account username
    default: root
    hidden: true

resources:
  wordpress_config:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: db_name
        - name: db_user
        - name: db_password
        - name: db_ipaddr
      group: script
      config: { get_file: wp_install.sh }

  db_config:
    type: OS::Heat::SoftwareConfig
    properties:
      inputs:
        - name: db_rootpassword
        - name: db_name
        - name: db_user
        - name: db_password
        - name: db_ipaddr
      group: script
      config: { get_file: db_install.sh }

  wordpress_deployment:
    type: OS::Heat::SoftwareDeployment
    depends_on: db_deployment
    properties:
      config:
        get_resource: wordpress_config
      server:
        get_resource: webserver_instance
      input_values:
        db_name: { get_param: db_name }
        db_user: { get_param: db_username }
        db_password: { get_param: db_password }
        db_ipaddr: { get_attr: [ dbserver_instance, first_address ] }   

  db_deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:
        get_resource: db_config
      server:
        get_resource: dbserver_instance
      input_values:
        db_rootpassword: { get_param: db_root_password }
        db_name: { get_param: db_name }
        db_user: { get_param: db_username }
        db_password: { get_param: db_password }
        db_ipaddr: { get_attr: [ dbserver_instance, first_address ] }   

  webserver_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: web_private_port }
      user_data_format: SOFTWARE_CONFIG

  dbserver_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: db_private_port }
      user_data_format: SOFTWARE_CONFIG

  web_private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network_id_private }
          
  db_private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network_id_private }

  web_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: web_private_port }

outputs:
  WebsiteURL:
    description: URL for Wordpress wiki
    value:
      str_replace:
        template: http://host/wordpress
        params:
          host: {get_attr: [ web_floating_ip, floating_ip_address ] }

