heat_template_version: 2013-05-23

description: >
  A template to create a Softlayer Virtual Machine.

parameters:
  chef_server_ip:
    type: string
    description: IP address of Chef Server
    default: '198.11.200.214'
  chef_valid_pem_url:
    type: string
    description: URL of Validation Key to Chef Server
    default: 'http://198.11.200.214:8080/validation.pem'
  chef_env:
    type: string
    description: Chef Env of Smart Workforce 
    default: 'smart_workforce'
  ui_host_name:
    type: string
    description: Hostname of UI Virtual Machine.
    default: xue-ui-server
  bi_host_name:
    type: string
    description: Hostname of BI Virtual Machine.
    default: xue-bi-server
  spss_host_name:
    type: string
    description: Hostname of SPSS Virtual Machine.
    default: xue-spss-server
  domain:
    type: string
    description: Domain name of VM.
    default: heaton.softlayer.com
  cpu_number:
    type: number
    description: CPU number of VM.
    default: 1
  memory:
    type: number
    description: Memory capacity of VM.
    default: 1024
  hourly:
    type: string
    description: Whether VM is charged hourly.
    default: True
  datacenter:
    type: string
    description: Short name of datacenter where VM is located.
    default: 'sjc01'
  os_code:
    type: string
    description: OS VM using.
    default: 'REDHAT_6_64'
  image:
    type: string
    description: The name of image used to create VM.
    default: 'rhel-softcfg-chef'
  image_id:
    type: string
    description: The ID of image used to create VM.
    default: 'a6d0c3cb-9e3a-459a-8789-76e568cd2a2a'
  public_vlan:
    type: string
    description: The name of public vlan used to create VM.
    default: 'ASC-public'
  private_vlan:
    type: string
    description: The name of private vlan used to create VM.
    default: 'ASC-private'
  ssh_keys:
    type: string
    description: The list of SSH keys used to inject into VM when boot it up.
    default: ['heaton', 'openstack-softlayer', 'os-sl-hk']
  sl_user:
    type: string
    description: User name of Softlayer account.
    default: 'shutao1'
  sl_apikey:
    type: string
    description: API key of Softlayer account.
    default: '3f3faab8d8f738ac6f8c232de59d3c11d5383a4d4462f369e11422079e889d46'

resources:
  vm_ui:
    type: SL::Compute::VM
    properties:
      host_name: { get_param: ui_host_name }
      domain: { get_param: domain }
      cpus: { get_param: cpu_number }
      memory: { get_param: memory }
      hourly: { get_param: hourly }
      datacenter: { get_param: datacenter }
      image_id: { get_param: image_id }
      disk_type: 'SAN'
      public_vlan: { get_param: public_vlan }
      private_vlan: { get_param: private_vlan }
      ssh_keys: { get_param: ssh_keys }
      sl_user: {get_param: sl_user}
      sl_apikey: {get_param: sl_apikey}
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo 'hello, $vm_name.$domain!' >> /root/$vm_name.tmp
          params:
            $vm_name: { get_param: ui_host_name }
            $domain: {get_param: domain}
      user_data_format: 'SOFTWARE_CONFIG'

  vm_bi:
    type: SL::Compute::VM
    properties:
      host_name: { get_param: bi_host_name }
      domain: { get_param: domain }
      cpus: { get_param: cpu_number }
      memory: { get_param: memory }
      hourly: { get_param: hourly }
      datacenter: { get_param: datacenter }
      image_id: { get_param: image_id }
      disk_type: 'SAN'
      public_vlan: { get_param: public_vlan }
      private_vlan: { get_param: private_vlan }
      ssh_keys: { get_param: ssh_keys }
      sl_user: {get_param: sl_user}
      sl_apikey: {get_param: sl_apikey}
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo 'hello, $vm_name.$domain!' >> /root/$vm_name.tmp
          params:
            $vm_name: { get_param: bi_host_name }
            $domain: {get_param: domain}
      user_data_format: 'SOFTWARE_CONFIG'

  vm_spss:
    type: SL::Compute::VM
    properties:
      host_name: { get_param: spss_host_name }
      domain: { get_param: domain }
      cpus: { get_param: cpu_number }
      memory: { get_param: memory }
      hourly: { get_param: hourly }
      datacenter: { get_param: datacenter }
      image_id: { get_param: image_id }
      disk_type: 'SAN'
      public_vlan: { get_param: public_vlan }
      private_vlan: { get_param: private_vlan }
      ssh_keys: { get_param: ssh_keys }
      sl_user: {get_param: sl_user}
      sl_apikey: {get_param: sl_apikey}
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            echo 'hello, $vm_name.$domain!' >> /root/$vm_name.tmp
          params:
            $vm_name: { get_param: spss_host_name }
            $domain: {get_param: domain}
      user_data_format: 'SOFTWARE_CONFIG'


  config:
    type: OS::Heat::SoftwareConfig
    properties:
    properties:
      inputs:
        - name: CHEF_SERVER_IP
          type: String
        - name: CHEF_VALID_PEM_URL
          type: String
        - name: CHEF_ENV
          type: String
        - name: CHEF_RUN_LIST
          type: String
        - name: CHEF_METADATA
          type: String
      outputs:
        - name: result
      group: chef

  deployment_modeler:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        CHEF_SERVER_IP: { get_param: chef_server_ip }
        CHEF_VALID_PEM_URL: { get_param: chef_valid_pem_url }
        CHEF_ENV: { get_param: chef_env }
        CHEF_RUN_LIST: 'role[spss_modeler_16]'
        CHEF_METADATA: 'none'
      config:
        get_resource: config
      server:
        get_resource: vm_spss
  deployment_batch:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        CHEF_SERVER_IP: { get_param: chef_server_ip }
        CHEF_VALID_PEM_URL: { get_param: chef_valid_pem_url }
        CHEF_ENV: { get_param: chef_env }
        CHEF_RUN_LIST: 'role[spss_batch_16]'
        CHEF_METADATA: 'none'
      config:
        get_resource: config
      server:
        get_resource: vm_spss
  deployment_analytics:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        CHEF_SERVER_IP: { get_param: chef_server_ip }
        CHEF_VALID_PEM_URL: { get_param: chef_valid_pem_url }
        CHEF_ENV: { get_param: chef_env }
        CHEF_RUN_LIST: 'role[spss_analytics]'
        CHEF_METADATA: 'none'
      config:
        get_resource: config
      server:
        get_resource: vm_spss
  deployment_postgresql:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        CHEF_SERVER_IP: { get_param: chef_server_ip }
        CHEF_VALID_PEM_URL: { get_param: chef_valid_pem_url }
        CHEF_ENV: { get_param: chef_env }
        CHEF_RUN_LIST: 'role[postgresql]'
        CHEF_METADATA: 'none'
      config:
        get_resource: config
      server:
        get_resource: vm_ui

outputs:
  Access:
    description: access to vm
    value:
      str_replace:
        template: $public_ip,$private_ip,$password,$uuid
        params:
          $public_ip: { get_attr: [vm_ui, PublicIp] }
          $private_ip: { get_attr: [vm_ui, PrivateIp] }
          $password: { get_attr: [vm_ui, passwords] }
          $uuid: { get_attr: [vm_ui, uuid] }
